### ISSUE TITLE
[Bug]: Text area - Problems with string length

### ISSUE THREAD

**Issue by palicepta** [Status-Page/Status-Page#447]
### Description of the Bug

Please extend the string length for Text aria in Incidents and Maintenance.
Now you can post a maximum of 1024 characters.

### Expected behavior

Also if this is possible, please set simple text without Markdown syntax. Because it does not work fine.

Otherwise the panel is very cool, you are a very cool expert, thank you in advance.

### Reproduction

1. Go to 'Maintenances -> Maintenances'
2. Click on 'Add'
3. Scroll down to 'Maintenance Update'
4. Insert in Text area more than 1024 characters, and try to create the new Maintenance.
5. See error

### Version

= 2.0.0 (Stable)

### Information about your Device

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [safari]

### Relevant log output

```shell
statuspage@statuspage ERROR:  value too long for type character varying(1024)
statuspage@statuspage STATEMENT:  INSERT INTO "maintenances_maintenanceupdate" ("created", "last_updated", "text", "new_status", "maintenance_id", "status", "user_id") VALUES ('2022-12-16T12:40:15.976833+00:00'::timestamptz, '2022-12-16T12:40:15.976845+00:00'::timestamptz, 'yuxepknagwckwgfsehlrvqwklfrkskqbcwtdiqdepiugjwwrshpnpibqcbssliidjnrvdeakpmjsmbylbkjhlooogphgwqljndmsgcupmisnnsnpemtaalxckeveesaklyflhmmtiiofpzmqrycvimuqbdbulokcgqbvnsosbiyxxwhtefqvgipqfaubfzistyynduixzzytjytsvurwcwsliqvhinnvjgqiynsznqtbmfoqxqmqkrmtobzndfgdrtkdcesmoqkyafgoavsygdgowjbwevlqeljfoulzgabvdlyzrrumztgledosvqkeufxlpqbvatrfvwkgszeujqdvxifialtwklfdgqrqvyouabobwmmjydrzerapqbkixsdcbsouycabamdcayyudrsxwtjhvnjziqwbncivdyrhsoagzucjveuwdmnfhuyappdiykhgjnhyabfjvsoilopjwsjveoylefugsplvkmnwlutxsscmfikuilbgxowzloverxnjaynkvkupdbwniwjhaxdgubntiaoswdysanjyjbtnscwqptxtehevdjexeywberwdfbhudizalzlabugesujnoysyjdqsjwyvxyfjrfsauntngxhznrqkretoszymssiwgcjdghgllqxhrrquqsyazhcbwomftujjqkxuvatnjhncfpisulaobxpthsgslsksmxmnrqdaviqilbjhdelgiglyusveanrmrbhjnxlqxptqwvikbypnhwukatwryjxgwyeitpafaazanlclqbxsuyrxlacucnniwasfumbvxcuprrfkslhvxjpznjbeyuvxrokzfrqtxrhcqofyrxpcxxgvdchyuzbbitylsdsrfdpnbfaxqbmezyonuhbzgjvvrmsromekpwerferztycpcnkdfrchpykdtidoeoekzqcutlhrltxknqcgdegzhsqrdlipnjgbpseosnkxtubfeiwkenmkkhwjvfmbigsghyrdtnyngdsfgkjgg', false, 26, 'schedule', 1) RETURNING "maintenances_maintenanceupdate"."id"
```

**Comment by HerrTxbias** [comment]
Hello,

thank you for your Bug Report! Could you tell me more about the problems with Markdown? Do you have any examples so that I can understand and possibly fix them? I would not like to remove the Markdown support.

**Comment by palicepta** [comment]
Hello Mr. [HerrTxbias](https://github.com/HerrTxbias)

Based on this article:
https://www.markdownguide.org/basic-syntax/#paragraphs-1

Between paragraphs should be a blank line, but unfortunately there is none, I would also like to do without specifying tags.
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/112872766/208110959-42b6ade1-273b-4f94-8f95-9d2c5685ef37.png">
<img width="986" alt="image" src="https://user-images.githubusercontent.com/112872766/208111176-9648fed5-1489-4ec3-b554-22b5907d9fe9.png">
