### ISSUE TITLE
[Feature]: Improve Markdown Rendering

### ISSUE THREAD

**Issue by HerrTxbias** [Status-Page/Status-Page#449]
Regarding: https://github.com/Status-Page/Status-Page/issues/447#issuecomment-1354797192

**Comment by palicepta** [comment]
Hi @HerrTxbias,

Do you have any updates on this issue?

**Comment by HerrTxbias** [comment]
@palicepta I have released this as a beta release: https://github.com/Status-Page/Status-Page/releases/tag/v2.1-beta5

**Comment by palicepta** [comment]
@HerrTxbias Hello again,

I have checked the new updated version, but anyway, the markdown does not work correctly:

For this structure:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/112872766/219351537-67ffeef4-ff26-484f-a365-80e16b78b66a.png">

Need to write some like this:
`OUR company:
<br><br>
Sehr geehrter Kunde,
<br><br>
wir möchten Sie darüber informieren, dass während der angekündigten Wartungsarbeiten ein unerwartetes Problem aufgetreten ist.
<br><br>
Unsere Außenanbindung war für etwa 10 Minuten instabil. Während dieser Zeit konnten Sie möglicherweise nicht von außen auf Ihre Dienste zugreifen.
<br><br>
Nachdem wir dieses Problem behoben haben, werden wir mit den geplanten Wartungsarbeiten fortfahren.
<br>
---------------------------
<br><br>
Dear Customer,
<br><br>
We would like to inform you, that during the announced maintenance work we’ve faced an unexpected issue.
<br><br>
Our outside connection wasn't stable for around 10min. During this time, you might not been able to access your services from outside.
<br><br>
After resolving this issues, we're continue with planned maintenance work afterwards.`

Could you please check and if it's possible:
Fix it to use the markdown clear line without the tags <br>

Thank you in advance.

**Comment by HerrTxbias** [comment]
Hi, i've wrote your Text without any HTML tags and everything is working as expected. It looks like an old version of the stylesheet is loaded. Please try clearing your cache and any other caches from other services like Cloudflare.

Raw Text:
```
Sehr geehrter Kunde,

wir möchten Sie darüber informieren, dass während der angekündigten Wartungsarbeiten ein unerwartetes Problem aufgetreten ist.

Unsere Außenanbindung war für etwa 10 Minuten instabil. Während dieser Zeit konnten Sie möglicherweise nicht von außen auf Ihre Dienste zugreifen.

Nachdem wir dieses Problem behoben haben, werden wir mit den geplanten Wartungsarbeiten fortfahren.

------------------

Sehr geehrter Kunde,

wir möchten Sie darüber informieren, dass während der angekündigten Wartungsarbeiten ein unerwartetes Problem aufgetreten ist.

Unsere Außenanbindung war für etwa 10 Minuten instabil. Während dieser Zeit konnten Sie möglicherweise nicht von außen auf Ihre Dienste zugreifen.

Nachdem wir dieses Problem behoben haben, werden wir mit den geplanten Wartungsarbeiten fortfahren.
```

Result:
![image](https://cdn.herrtxbias.net/2023-02-17_10-55-24_aa5bca81-797e-4905-8f09-95cdd7f2aea3.png)

**Comment by palicepta** [comment]
Dear @HerrTxbias

You are right, it doesn't work on Safari Version 13.1.3.
And when I tried it on Google it worked fine. 

Thank you for your answer and your pretty work.
