### ISSUE TITLE
[Bug]: Unable to login after install

### ISSUE THREAD

**Issue by Phhere** [Status-Page/Status-Page#456]
### Description of the Bug

The first login requires a otp pin but it is not possible to add a device without login

### Expected behavior

Manage.py command should be available to setup otp or disable otp

### Reproduction

1. Install
2. Login at /admin/

### Version

> 2.0.0 (Preview)

### Information about your Device

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Browser [e.g. chrome, safari] Firefox 
 - Version [e.g. 22] 100+

**Comment by HerrTxbias** [comment]
Hi, you can login at `/dashboard` without an OTP, and then setup your OTP there.
However I will look at adding a command to setup OTP.
