### ISSUE TITLE
[Feature]: Incident/maintenance templates

### ISSUE THREAD

**Issue by HerrTxbias** [Status-Page/Status-Page#467]
### Discussed in https://github.com/Status-Page/Status-Page/discussions/466

<div type='discussions-op-text'>

<sup>Originally posted by **BornTKill** February 16, 2023</sup>
Dear,

I would like to have template when opening an incident/maintenance.
Do you plan to do that ? Or only with API ?</div>

**Comment by BornTKill** [comment]
Hello @HerrTxbias 

Thank you for this quick release.
I have created a template maintenance but don't now how to use it when creating a new scheduled maintenance.

Thank you for your clarification.

**Comment by BornTKill** [comment]
![image](https://user-images.githubusercontent.com/16973237/225924978-f9a2ebe1-c98a-4343-b5aa-ebf0e1dfd1e4.png)

I found.

**Comment by BornTKill** [comment]
Should be great to have a template selection when creating new incident/maintenance.

**Comment by HerrTxbias** [comment]
Could you open two separate issues for those two things, so i can have a look at these things later?

**Comment by BornTKill** [comment]
Sure :)
