### ISSUE TITLE
[Bug]: Incident/Maintenance template character escaping

### ISSUE THREAD

**Issue by BornTKill** [Status-Page/Status-Page#493]
### Description of the Bug

Dear,

i have create a incident template and a maintenance template. 

![image](https://user-images.githubusercontent.com/16973237/225929221-fe5b652d-b82f-4a5c-bfb0-3683268bc4a2.png)

But when creating an incident/maintenance from this template is not working

![image](https://user-images.githubusercontent.com/16973237/225929349-6df3ebfd-cb82-4ce3-bafd-df05367e6162.png)

![image](https://user-images.githubusercontent.com/16973237/225929396-c11f4369-4d79-49f5-b6de-607aa3b1341e.png)

it's empty.

![image](https://user-images.githubusercontent.com/16973237/225929433-ce87d1bc-08bf-41b2-8fbd-392ab149d300.png)

### Expected behavior

Pre fill incident/maintenance from template.

### Reproduction

.

### Version

> 2.0.0 (Preview)

### Information about your Device

.

**Comment by HerrTxbias** [comment]
Hi, unfortunately I can not recreate the behavior. On my test instance as well as on my productive instances the templates work without any problems.

If you click on the button, can you see the query parameters in your URL?
It should look like this:
`https://status.domain.tld/dashboard/maintenances/add/?title=Title&status=schedule&impact=maintenance&visibility=True&components=2&update_component_status=True&text=Maintenance%20Text`

**Comment by BornTKill** [comment]
https://XXXXXX/dashboard/maintenances/add/?title=#1%20template%20maitenance%20title&status=schedule&impact=maintenance&visibility=True&components=1&components=2&components=3&components=4&components=5&update_component_status=True&text=#text%20in%20template%20maintenance

Here is the link I have when I click on the button.

**Comment by BornTKill** [comment]
Dear,

I think, I found the problem.

# (and maybe all special char) in a field is breaking the functionnality.

**Comment by BornTKill** [comment]
@HerrTxbias Good morning. I try your patch but I still have the same issue.

**Comment by BornTKill** [comment]
With this URL it's OK.

https://XXXXXXdashboard/maintenances/add/?title=%23%20template%20maitenance%20title&status=schedule&impact=maintenance&visibility=True&components=1&components=2&components=3&components=4&components=5&update_component_status=True&text=%23text%20in%20template%20maintenance
