### ISSUE TITLE
[Bug]: New incident/maintenance are using incidentupdates/maintenanceupdates email template

### ISSUE THREAD

**Issue by BornTKill** [Status-Page/Status-Page#500]
### Description of the Bug

Dear @HerrTxbias 

When creating a new incident/maintenance, we receive email for update and not the one for creation.

### Expected behavior

receive creation email.

### Reproduction

...

### Version

> 2.0.0 (Preview)

### Information about your Device

...

**Comment by HerrTxbias** [comment]
Could you provide some more details on this?
Please also have a look at the finished background tasks in the admin panel, to see if the emails for those events have been sent.
I receive an E-Mail for Incident Creation and Incident Update Creation.

**Comment by BornTKill** [comment]
Dear,

I also receive my email but it's always the update template that is used.
When a create an new incident or maintenance I would like to receive template for creation and not for update.

/opt/status-page/statuspage/templates/emails/maintenances/created.html  and not /opt/status-page/statuspage/templates/emails/maintenanceupdates/created.html

**Comment by HerrTxbias** [comment]
Hey, sorry but I can't reproduce this.

I receive two emails:
1. An email for the incident / maintenance creation
2. Separate email for the incident / maintenance *update* creation

**Comment by BornTKill** [comment]
Dear @HerrTxbias,

I have fully reinstall my statusage from scratch 2.2.1 and the issue is here:
When creating a new incident I receive

![image](https://user-images.githubusercontent.com/16973237/227141104-361fc261-9457-4725-86b9-e243ef969df2.png)

As you can see it's not seen as a creation event but an update event.

Details 

![image](https://user-images.githubusercontent.com/16973237/227141438-cb7bd6b6-b9dc-4605-9be0-169e14588752.png)

![image](https://user-images.githubusercontent.com/16973237/227141509-5d376fa9-4990-40e9-b0e6-4528ec82c56c.png)

When I click on item 4

![image](https://user-images.githubusercontent.com/16973237/227141634-4f4af9f9-6c8f-42ac-8451-ad2082dc64aa.png)

Associated task

![image](https://user-images.githubusercontent.com/16973237/227141967-25f7c09e-3547-4477-9ee4-b6777c34bd67.png)

**Comment by BornTKill** [comment]
For maintenance

![image](https://user-images.githubusercontent.com/16973237/227142565-1c08c207-1f6a-4558-83f2-57d73cb2409a.png)

![image](https://user-images.githubusercontent.com/16973237/227142618-2ddef6a0-fdc7-422a-8568-c8572ebc263b.png)

![image](https://user-images.githubusercontent.com/16973237/227142655-3dbf84c1-6026-4187-bc56-ece18d8c24cc.png)

![image](https://user-images.githubusercontent.com/16973237/227142736-36597813-b2cb-45f3-bb0d-bddc44a635a1.png)

![image](https://user-images.githubusercontent.com/16973237/227142859-31e6b463-f87c-4c97-bc8b-ed8d9ed01344.png)

![image](https://user-images.githubusercontent.com/16973237/227143061-eb0d324d-7dfb-4bc1-b29c-34c5f0c57299.png)

![image](https://user-images.githubusercontent.com/16973237/227143142-22104d3d-16b5-4525-93cf-2609715039fe.png)

![image](https://user-images.githubusercontent.com/16973237/227143182-b3073a6e-d3cb-48ec-9543-56215d229a99.png)

![image](https://user-images.githubusercontent.com/16973237/227143222-74fe65ed-55bb-4005-aa84-1477558c6231.png)

**Comment by HerrTxbias** [comment]
Is there a failed send_mail Task?

**Comment by BornTKill** [comment]
When I "grep" the email content it match

![image](https://user-images.githubusercontent.com/16973237/227143994-9e0551b6-6eae-43f8-982a-aa7fc403cc20.png)

and never 

![image](https://user-images.githubusercontent.com/16973237/227144126-84bce746-d219-4baa-8e94-007f812027d1.png)

**Comment by BornTKill** [comment]
> Is there a failed send_mail Task?

![image](https://user-images.githubusercontent.com/16973237/227144253-77f0a30b-eb54-4645-81cc-9d98cdfdbf43.png)

**Comment by BornTKill** [comment]
But after this I have successful on both

![image](https://user-images.githubusercontent.com/16973237/227145647-fd45668a-5d90-447a-a7c2-272b8238bb9c.png)

![image](https://user-images.githubusercontent.com/16973237/227145705-51cc2310-7f94-4d12-a531-8ebb23a3936b.png)

**Comment by BornTKill** [comment]
I think (and maybe I am wrong), the email creation template is never used because Text filed is mandatory.
So as long as there is a text, this is considered as an update and not a creation.

**Comment by HerrTxbias** [comment]
> I think (and maybe I am wrong), the email creation template is never used because Text field is mandatory. So as long as there is a text, this is considered as an update and not a creation.

The email creation template is always used (see https://github.com/Status-Page/Status-Page/blob/d9483caa06d905ed6b22228d9064b5d74734a0f0/statuspage/incidents/signals.py#L21-L26). But it seems like the identical function names are an issue here.

**Comment by BornTKill** [comment]
I confirm the fix ! thanks @HerrTxbias
