### ISSUE TITLE
[Feature]: Send 1 email instead of 2 when creating a maintenance/incident

### ISSUE THREAD

**Issue by BornTKill** [Status-Page/Status-Page#504]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when creating a new incident/maintenance, I receive 2 emails:
 - Creation email without text information
 - Update email containing text information that I used during initial creation.

### Describe the solution you'd like

Receiving only 1 creation email when creating incident/maintenance that contains all the information.
Receiving 1 update email when updating an existing incident/maintenance.

### Describe alternatives you've considered

...

### Additional context

...

**Comment by heiko-ma** [comment]
I second this, there has to be a change in the logic when creating an incident/maintenance:
- When an incident is created, there should be a api-field "text" which contains the initial information which is submitted when creating the entry, it could look like this in the GUI:
<img width="1780" alt="yaBbZ9clZF" src="https://user-images.githubusercontent.com/64192965/227954128-278b04c0-b425-496f-9367-4e7bef40363e.png">

- Afterwards, when you want to provide an update, there could be a button beside the edit/delete button, this could look like this:
<img width="1814" alt="F2GQ45RzCu" src="https://user-images.githubusercontent.com/64192965/227954401-050bb46b-d4d0-4214-9436-dec3510deb22.png">
  The incident update dialog could look like this:
<img width="1785" alt="U0eoozRivL" src="https://user-images.githubusercontent.com/64192965/227955349-4d025bb2-4bc2-4f5e-bdf3-9f6b15724e0e.png">

The same logic can be used for the maintenance creation/update mechanism. In my opinion, this would improve the workflow for the incident management.

I must say that I'm glad that I found this tool, we're currently using cachet but your tool is way better and fixes the flaws cachet has. Keep up the good work!
