### ISSUE TITLE
[Bug]: Markdown rendering is not applied in email

### ISSUE THREAD

**Issue by BornTKill** [Status-Page/Status-Page#506]
### Description of the Bug

Good morning @HerrTxbias 

When adding a markdown content, the text is well formatted in status page but the email is not.

Here the result on my status page 

![image](https://user-images.githubusercontent.com/16973237/227992248-ffc06d3a-0d4b-476e-b04a-34a966a838f4.png)

Corresponding code :

![image](https://user-images.githubusercontent.com/16973237/227992322-5c0b9f49-59be-4454-b8cb-635b94633f96.png)

Email rendering :

![image](https://user-images.githubusercontent.com/16973237/227992653-3309b986-784f-41b7-bb12-dc6387647534.png)

Here is the email source

![image](https://user-images.githubusercontent.com/16973237/227992048-9d838d81-f23c-45b6-8e95-f070459cd8ea.png)

### Expected behavior

...

### Reproduction

...

### Version

> 2.0.0 (Preview)

### Information about your Device

...

**Comment by sparthe123** [comment]
I'm also having issue with Email rendering , in my case it html is broken and email text are not formatted .

https://share.anysnap.app/fWKUFQYFHOdQ

https://share.anysnap.app/fkN52LM6QM46

**Comment by sparthe123** [comment]
Hi, @HerrTxbias 

I'm still facing the same issue, when I receive email html is broken. Can you please help to fix this issue..

**Comment by HerrTxbias** [comment]
The Issue here is with Gmail itself. It seems like they don't support some of the style properties I've used.
Here is one, for example: https://www.caniemail.com/search/?s=flex-direction%3Acolumn

**Comment by sparthe123** [comment]
Oh okay, any work around for that ?, because our subscriber going to be Google workspace users.

**Comment by HerrTxbias** [comment]
There is no workaround for you, other than not using Google Workspace :D 

Jokes aside, i need to style those emails differently with properties, that are supported among the most common email clients and services.

**Comment by thorm42** [comment]
Hello,

For your information, `display: flex` is not working in Gmail.

I change all the mail template and replace the div with flex into a table.

Now it is OK

![Capture d'écran 2023-04-04 115429](https://user-images.githubusercontent.com/119916/229757055-dcbb5171-7b0c-4747-a2e2-5347d6801b0c.png)

**Comment by HerrTxbias** [comment]
Would you open a PR with the changes you've made? That would make this a little bit easier for me.

**Comment by thorm42** [comment]
Sorry I am not a developper. I don't know how to make a PR.

I made some changes of the content but you can take the structure (color, content,...) : 

statuspage\templates\base\layout_email.html
```
{% extends 'base/base_email.html' %}

{% block body %}
<div>
	<div style="margin-right: auto; margin-left: auto; text-align: center"><img src="xxxx" width="200px" /></div>
	<div style="background-color: rgb(92, 89, 245);text-align: center; font-size: 1.5rem; line-height: 2rem; padding-top: 1rem; padding-bottom: 1rem;"><a href="{{ site_url }}" style="text-decoration-line: none; color: white">{{ site_title }}</a></div>
	<div style="margin-right: auto; margin-left: auto; background: linear-gradient(rgb(226, 236, 255), rgb(255, 255, 255));color: black; padding: 1.5rem; height: 100%;">
	  {% block content %}{% endblock %}
	</div>
</div>
{% endblock body %}
```

statuspage\templates\emails\maintenances\created.html
```
{% extends 'base/layout_email.html' %}

{% block content %}
<table style="background: white; width:500px; margin-right: auto; margin-left: auto; padding: 1rem; border-radius: 0.5rem; border: 0" width="500px">
	<tr><td style="font-size: 1.125rem; line-height: 1.75rem;">Dear client,</td></tr>
	<tr><td style="padding-top: 0.5rem;">The maintenance "{{ maintenance.title }}" has been created.</td></tr>
	<tr><td style="padding-top: 1rem;">It has the following schedule:</td></tr>
	<tr><td style="padding-top: 0.5rem;">Begin: {{ maintenance.scheduled_at }}</td></tr>
	<tr><td style="padding-top: 0.5rem;">End: {{ maintenance.end_at }}</td></tr>
	<tr><td style="padding-top: 1rem;">Maintenance status: <strong>{% if update.new_status %}{{ update.get_status_display }}{% else %}Update{% endif %}</strong></td></tr>
	<tr><td style="padding-top: 1rem;">Description:</td></tr>
	<tr><td style="padding-top: 0.5rem;">{{ update.text|markdown }}</td></tr>
	{% if components|length > 0 %}
	<tr><td style="padding-top: 0.5rem;">The following components are affected:</td></tr>
	<tr><td>
	  <ul>
		{% for component in components %}
		  <li>{{ component.name }}</li>
		{% endfor %}
	  </ul>
	</td></tr>
	{% endif %}
	<tr><td> <div style="border-radius: 0.375rem; padding: 0.25rem 0.5rem; background: #5C59F5; width: 120px; text-align: center; margin-right: auto; margin-left: auto"><a href="{{ site_url }}" style="text-decoration-line: none; color: #ffffff; font-size: 1.25rem; line-height: 1.75rem;">View Status</a></div></td></tr>
	<tr><td style="padding-top: 0.5rem;">Kind regards,<br> {{ site_title }} </td></tr>
	
	<tr><td style="padding-top: 0.5rem;"><hr/></td></tr>
	  <tr><td style="font-size: 0.75rem;color: #A1A1AA; padding-top: 0.5rem; line-height: 1.25rem;text-align: center;">
		More actions<br>
		Manage: {{ management_url }}<br>
		Unsubscribe: {{ unsubscribe_url }}
	  </td></tr>
</table>
{% endblock content %}
```
