### ISSUE TITLE
[Feature]: Choose the components status on maintenance/incident

### ISSUE THREAD

**Issue by thorm42** [Status-Page/Status-Page#536]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I make a maintenance or an incident. I can not choose the components status.

For maintenance, the status is always to "Operational"
For incident, the status is always to "Degraded Performance"

Is it possible to do a drop menu to choose the status?

Thank you.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by HerrTxbias** [comment]
The Component Status is being determined by the Incident Impact:
https://github.com/Status-Page/Status-Page/blob/main/statuspage/incidents/forms/models.py#L78-L82
https://github.com/Status-Page/Status-Page/blob/main/statuspage/utilities/utils.py#L217-L224

**Comment by thorm42** [comment]
Thank you!
And for the maintenance? It is possible to put the components to in maintenance?
Thank you

**Comment by HerrTxbias** [comment]
If you add a Maintenance and you enable the automatic status update for components, the selected components will be set to "Maintenance".
