### ISSUE TITLE
[Bug]: Emails are not being delivered. 

### ISSUE THREAD

**Issue by ArunNathan** [Status-Page/Status-Page#539]
### Description of the Bug

The emails have suddenly ceased triggering. 

We have received emails previously. We edited the created.html and created.txt file for the format changes and the emails are stopped triggering.. 

### Expected behavior

Can someone help us with the logs path. We are not sure, where to check the email logs. 

### Version

> 2.0.0 (Preview)

### Information about your Device

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by HerrTxbias** [comment]
You probably made some mistakes in the templates, which prevents them from rendering in django, so this is not an issue with the product itself, i believe.

**Comment by ArunNathan** [comment]
Yes, We have restored the code. it's working..
