### ISSUE TITLE
[Feature]: Make 2FA deactivatable

### ISSUE THREAD

**Issue by mabezi** [Status-Page/Status-Page#545]
### Is your feature request related to a problem? Please describe.

It is certainly a useful feature, but it would be better if you could disable it. Especially when multiple people use the same access, it is not possible to use 2FA properly.

Apart from that, 2FA is fatally broken, but that's another topic.

### Describe the solution you'd like

An configuration option to disable 2FA.
Alternatively a per account setting, if this is possible in Django.

### Describe alternatives you've considered

Right now I just abuse a bug or I use the backup tokens.

**Comment by HerrTxbias** [comment]
You don't have to use 2FA on an account, it is completely optional.

**Comment by mabezi** [comment]
Then why do I have to enter an OTP token if I want to directly log in to the admin panel? (`/admin/`)

**Comment by HerrTxbias** [comment]
This is unfortunately a drawback that comes from the library I use for the OTPs. However, this only applies to the direct login to the admin panel.

**Comment by mabezi** [comment]
So it is not possible to deactivate this 2FA query, is it?

**Comment by mabezi** [comment]
If that is the case, it would be good to document this. I assumed an bug first, especially since the dashboard indicates "2FA required" for the Admin-Interface.

At this point also thank you for the clarification.

**Comment by HerrTxbias** [comment]
Yeah, if you want to login directly into the admin panel, there is currently no way to deactivate this 2FA query.
