### ISSUE TITLE
[Feature]: Webhook Integration for Notification

### ISSUE THREAD

**Issue by HerrTxbias** [Status-Page/Status-Page#553]
### Discussed in https://github.com/Status-Page/Status-Page/discussions/532

<div type='discussions-op-text'>

<sup>Originally posted by **sparthe123** March 31, 2023</sup>
Can we have the Webhook integration for notification ? 

this helps to push notification to more platforms. </div>

**Comment by HerrTxbias** [comment]
@sparthe123 Would you prefer public Webhooks (So everyone could add a webhook), or Webhooks which only can be configured by admins? Or probably both?

**Comment by sparthe123** [comment]
@HerrTxbias , probably both with control setting that admin can open for anyone or just admin can do.
