### ISSUE TITLE
[Feature]: Can we show the timezone with the incidents. 

### ISSUE THREAD

**Issue by ArunNathan** [Status-Page/Status-Page#559]
### Is your feature request related to a problem? Please describe.

It will be much helpful when we mention the time zone of the issue happening. So it will be more clear to the readers to understand the time of the issue occurrence. 

### Describe the solution you'd like

My suggestion will be either we need to have the option to show the time zone there in the status page. 

In the dashboard, we can choose/select the timezone. 

or we need option to either show the timing as UTC or IST etc.. 

### Describe alternatives you've considered

The option to show the timezone of the issue occurrence.

**Comment by HerrTxbias** [comment]
You can adjust the Date Format strings to display the time zone in your configuration.py.

https://github.com/Status-Page/Status-Page/blob/main/statuspage/statuspage/configuration_example.py#L163-L168
Reference: https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#std-templatefilter-date
