### ISSUE TITLE
[Feature]: Make templates more practical to use

### ISSUE THREAD

**Issue by thorm42** [Status-Page/Status-Page#561]
### Is your feature request related to a problem? Please describe.

Hello,
Is it possible to make these changes to the templates?

1. When we do an update of a maintenance or an incident, if the title or component fields are not empty, do not replace them. This will avoid having to fill them again when we select a template
2. When creating a template, allow to choose the fields "Start automatically" and "End automatically".

Thank you very much!

### Describe the solution you'd like

1. When we do an update of a maintenance or an incident, if the title or component fields are not empty, do not replace them. This will avoid having to fill them again when we select a template
2. When creating a template, allow to choose the fields "Start automatically" and "End automatically".

### Describe alternatives you've considered

1. When we do an update of a maintenance or an incident, if the title or component fields are not empty, do not replace them. This will avoid having to fill them again when we select a template
2. When creating a template, allow to choose the fields "Start automatically" and "End automatically".

**Comment by HerrTxbias** [comment]
The first change will not be possible i think. But I'm able to add the second requested change.

**Comment by thorm42** [comment]
Thank you!
